import React, { createContext, useContext, useState, useEffect } from 'react';

// All world languages with their native names
export const LANGUAGES = {
  // Major Languages
  en: { name: 'English', native: 'English', flag: '🇺🇸' },
  es: { name: 'Spanish', native: 'Español', flag: '🇪🇸' },
  fr: { name: 'French', native: 'Français', flag: '🇫🇷' },
  de: { name: 'German', native: 'Deutsch', flag: '🇩🇪' },
  it: { name: 'Italian', native: 'Italiano', flag: '🇮🇹' },
  pt: { name: 'Portuguese', native: 'Português', flag: '🇵🇹' },
  ru: { name: 'Russian', native: 'Русский', flag: '🇷🇺' },
  zh: { name: 'Chinese', native: '中文', flag: '🇨🇳' },
  ja: { name: 'Japanese', native: '日本語', flag: '🇯🇵' },
  ko: { name: 'Korean', native: '한국어', flag: '🇰🇷' },
  ar: { name: 'Arabic', native: 'العربية', flag: '🇸🇦' },
  hi: { name: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' },
  bn: { name: 'Bengali', native: 'বাংলা', flag: '🇧🇩' },
  pa: { name: 'Punjabi', native: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  // European Languages
  nl: { name: 'Dutch', native: 'Nederlands', flag: '🇳🇱' },
  pl: { name: 'Polish', native: 'Polski', flag: '🇵🇱' },
  uk: { name: 'Ukrainian', native: 'Українська', flag: '🇺🇦' },
  cs: { name: 'Czech', native: 'Čeština', flag: '🇨🇿' },
  sk: { name: 'Slovak', native: 'Slovenčina', flag: '🇸🇰' },
  hu: { name: 'Hungarian', native: 'Magyar', flag: '🇭🇺' },
  ro: { name: 'Romanian', native: 'Română', flag: '🇷🇴' },
  bg: { name: 'Bulgarian', native: 'Български', flag: '🇧🇬' },
  el: { name: 'Greek', native: 'Ελληνικά', flag: '🇬🇷' },
  sv: { name: 'Swedish', native: 'Svenska', flag: '🇸🇪' },
  no: { name: 'Norwegian', native: 'Norsk', flag: '🇳🇴' },
  da: { name: 'Danish', native: 'Dansk', flag: '🇩🇰' },
  fi: { name: 'Finnish', native: 'Suomi', flag: '🇫🇮' },
  // Asian Languages
  th: { name: 'Thai', native: 'ไทย', flag: '🇹🇭' },
  vi: { name: 'Vietnamese', native: 'Tiếng Việt', flag: '🇻🇳' },
  id: { name: 'Indonesian', native: 'Bahasa Indonesia', flag: '🇮🇩' },
  ms: { name: 'Malay', native: 'Bahasa Melayu', flag: '🇲🇾' },
  tl: { name: 'Filipino', native: 'Filipino', flag: '🇵🇭' },
  ta: { name: 'Tamil', native: 'தமிழ்', flag: '🇮🇳' },
  te: { name: 'Telugu', native: 'తెలుగు', flag: '🇮🇳' },
  mr: { name: 'Marathi', native: 'मराठी', flag: '🇮🇳' },
  gu: { name: 'Gujarati', native: 'ગુજરાતી', flag: '🇮🇳' },
  kn: { name: 'Kannada', native: 'ಕನ್ನಡ', flag: '🇮🇳' },
  ml: { name: 'Malayalam', native: 'മലയാളം', flag: '🇮🇳' },
  my: { name: 'Burmese', native: 'မြန်မာ', flag: '🇲🇲' },
  km: { name: 'Khmer', native: 'ខ្មែរ', flag: '🇰🇭' },
  lo: { name: 'Lao', native: 'ລາວ', flag: '🇱🇦' },
  ne: { name: 'Nepali', native: 'नेपाली', flag: '🇳🇵' },
  si: { name: 'Sinhala', native: 'සිංහල', flag: '🇱🇰' },
  // Middle Eastern Languages
  fa: { name: 'Persian', native: 'فارسی', flag: '🇮🇷' },
  tr: { name: 'Turkish', native: 'Türkçe', flag: '🇹🇷' },
  he: { name: 'Hebrew', native: 'עברית', flag: '🇮🇱' },
  ur: { name: 'Urdu', native: 'اردو', flag: '🇵🇰' },
  // African Languages
  sw: { name: 'Swahili', native: 'Kiswahili', flag: '🇰🇪' },
  am: { name: 'Amharic', native: 'አማርኛ', flag: '🇪🇹' },
  ha: { name: 'Hausa', native: 'Hausa', flag: '🇳🇬' },
  yo: { name: 'Yoruba', native: 'Yorùbá', flag: '🇳🇬' },
  zu: { name: 'Zulu', native: 'isiZulu', flag: '🇿🇦' },
  af: { name: 'Afrikaans', native: 'Afrikaans', flag: '🇿🇦' },
  // Other Languages
  ca: { name: 'Catalan', native: 'Català', flag: '🇪🇸' },
  eu: { name: 'Basque', native: 'Euskara', flag: '🇪🇸' },
  gl: { name: 'Galician', native: 'Galego', flag: '🇪🇸' },
  hr: { name: 'Croatian', native: 'Hrvatski', flag: '🇭🇷' },
  sr: { name: 'Serbian', native: 'Српски', flag: '🇷🇸' },
  sl: { name: 'Slovenian', native: 'Slovenščina', flag: '🇸🇮' },
  lt: { name: 'Lithuanian', native: 'Lietuvių', flag: '🇱🇹' },
  lv: { name: 'Latvian', native: 'Latviešu', flag: '🇱🇻' },
  et: { name: 'Estonian', native: 'Eesti', flag: '🇪🇪' },
  is: { name: 'Icelandic', native: 'Íslenska', flag: '🇮🇸' },
  ga: { name: 'Irish', native: 'Gaeilge', flag: '🇮🇪' },
  cy: { name: 'Welsh', native: 'Cymraeg', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  mt: { name: 'Maltese', native: 'Malti', flag: '🇲🇹' },
  sq: { name: 'Albanian', native: 'Shqip', flag: '🇦🇱' },
  mk: { name: 'Macedonian', native: 'Македонски', flag: '🇲🇰' },
  bs: { name: 'Bosnian', native: 'Bosanski', flag: '🇧🇦' },
  ka: { name: 'Georgian', native: 'ქართული', flag: '🇬🇪' },
  hy: { name: 'Armenian', native: 'Հայերdelays', flag: '🇦🇲' },
  az: { name: 'Azerbaijani', native: 'Azərbaycan', flag: '🇦🇿' },
  kk: { name: 'Kazakh', native: 'Қазақ', flag: '🇰🇿' },
  uz: { name: 'Uzbek', native: 'Oʻzbek', flag: '🇺🇿' },
  mn: { name: 'Mongolian', native: 'Монгол', flag: '🇲🇳' },
};

// Translations for all UI strings
const translations = {
  en: {
    // Navigation
    chats: 'Chats',
    calls: 'Calls',
    status: 'Status',
    channels: 'Channels',
    community: 'Community',
    media: 'Media',
    games: 'Games',
    ai: 'AI',
    settings: 'Settings',
    // Settings
    general: 'General',
    language: 'Language',
    selectLanguage: 'Select Language',
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    notifications: 'Notifications',
    privacy: 'Privacy',
    help: 'Help',
    about: 'About',
    logout: 'Logout',
    // Chat
    typeMessage: 'Type a message...',
    search: 'Search',
    newChat: 'New Chat',
    newGroup: 'New Group',
    contacts: 'Contacts',
    online: 'Online',
    offline: 'Offline',
    typing: 'typing...',
    lastSeen: 'Last seen',
    today: 'Today',
    yesterday: 'Yesterday',
    // Auth
    welcomeBack: 'Welcome Back',
    createAccount: 'Create Account',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    continueWithGoogle: 'Continue with Google',
    continueWithApple: 'Continue with Apple',
    continueWithFacebook: 'Continue with Facebook',
    otherSignInOptions: 'Other sign-in options',
    email: 'Email',
    password: 'Password',
    username: 'Username',
    displayName: 'Display Name',
    forgotPassword: 'Forgot password?',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    // Actions
    send: 'Send',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    reply: 'Reply',
    forward: 'Forward',
    copy: 'Copy',
    // ALO Assistant
    aloAssistant: 'ALO Assistant',
    askAlo: 'Ask ALO anything...',
    listening: 'Listening...',
    tapToSpeak: 'Tap to speak',
    // Misc
    loading: 'Loading...',
    noMessages: 'No messages yet',
    startConversation: 'Start a conversation',
  },
  es: {
    chats: 'Chats',
    calls: 'Llamadas',
    status: 'Estado',
    channels: 'Canales',
    community: 'Comunidad',
    media: 'Multimedia',
    games: 'Juegos',
    ai: 'IA',
    settings: 'Ajustes',
    general: 'General',
    language: 'Idioma',
    selectLanguage: 'Seleccionar Idioma',
    appearance: 'Apariencia',
    darkMode: 'Modo Oscuro',
    lightMode: 'Modo Claro',
    notifications: 'Notificaciones',
    privacy: 'Privacidad',
    help: 'Ayuda',
    about: 'Acerca de',
    logout: 'Cerrar Sesión',
    typeMessage: 'Escribe un mensaje...',
    search: 'Buscar',
    newChat: 'Nuevo Chat',
    newGroup: 'Nuevo Grupo',
    contacts: 'Contactos',
    online: 'En línea',
    offline: 'Desconectado',
    typing: 'escribiendo...',
    lastSeen: 'Última vez',
    today: 'Hoy',
    yesterday: 'Ayer',
    welcomeBack: 'Bienvenido de Nuevo',
    createAccount: 'Crear Cuenta',
    signIn: 'Iniciar Sesión',
    signUp: 'Registrarse',
    continueWithGoogle: 'Continuar con Google',
    continueWithApple: 'Continuar con Apple',
    continueWithFacebook: 'Continuar con Facebook',
    otherSignInOptions: 'Otras opciones de inicio de sesión',
    email: 'Correo Electrónico',
    password: 'Contraseña',
    username: 'Nombre de Usuario',
    displayName: 'Nombre para Mostrar',
    forgotPassword: '¿Olvidaste tu contraseña?',
    dontHaveAccount: '¿No tienes una cuenta?',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    send: 'Enviar',
    cancel: 'Cancelar',
    save: 'Guardar',
    delete: 'Eliminar',
    edit: 'Editar',
    reply: 'Responder',
    forward: 'Reenviar',
    copy: 'Copiar',
    aloAssistant: 'Asistente ALO',
    askAlo: 'Pregúntale algo a ALO...',
    listening: 'Escuchando...',
    tapToSpeak: 'Toca para hablar',
    loading: 'Cargando...',
    noMessages: 'Sin mensajes aún',
    startConversation: 'Inicia una conversación',
  },
  fr: {
    chats: 'Discussions',
    calls: 'Appels',
    status: 'Statut',
    channels: 'Chaînes',
    community: 'Communauté',
    media: 'Médias',
    games: 'Jeux',
    ai: 'IA',
    settings: 'Paramètres',
    general: 'Général',
    language: 'Langue',
    selectLanguage: 'Sélectionner la Langue',
    appearance: 'Apparence',
    darkMode: 'Mode Sombre',
    lightMode: 'Mode Clair',
    notifications: 'Notifications',
    privacy: 'Confidentialité',
    help: 'Aide',
    about: 'À propos',
    logout: 'Déconnexion',
    typeMessage: 'Tapez un message...',
    search: 'Rechercher',
    newChat: 'Nouvelle Discussion',
    newGroup: 'Nouveau Groupe',
    contacts: 'Contacts',
    online: 'En ligne',
    offline: 'Hors ligne',
    typing: 'écrit...',
    lastSeen: 'Vu',
    today: "Aujourd'hui",
    yesterday: 'Hier',
    welcomeBack: 'Bon Retour',
    createAccount: 'Créer un Compte',
    signIn: 'Se Connecter',
    signUp: "S'inscrire",
    continueWithGoogle: 'Continuer avec Google',
    continueWithApple: 'Continuer avec Apple',
    continueWithFacebook: 'Continuer avec Facebook',
    otherSignInOptions: 'Autres options de connexion',
    email: 'E-mail',
    password: 'Mot de passe',
    username: "Nom d'utilisateur",
    displayName: "Nom d'affichage",
    forgotPassword: 'Mot de passe oublié?',
    dontHaveAccount: "Vous n'avez pas de compte?",
    alreadyHaveAccount: 'Vous avez déjà un compte?',
    send: 'Envoyer',
    cancel: 'Annuler',
    save: 'Sauvegarder',
    delete: 'Supprimer',
    edit: 'Modifier',
    reply: 'Répondre',
    forward: 'Transférer',
    copy: 'Copier',
    aloAssistant: 'Assistant ALO',
    askAlo: 'Demandez à ALO...',
    listening: 'Écoute...',
    tapToSpeak: 'Appuyez pour parler',
    loading: 'Chargement...',
    noMessages: 'Pas encore de messages',
    startConversation: 'Démarrer une conversation',
  },
  de: {
    chats: 'Chats',
    calls: 'Anrufe',
    status: 'Status',
    channels: 'Kanäle',
    community: 'Gemeinschaft',
    media: 'Medien',
    games: 'Spiele',
    ai: 'KI',
    settings: 'Einstellungen',
    general: 'Allgemein',
    language: 'Sprache',
    selectLanguage: 'Sprache Auswählen',
    appearance: 'Erscheinungsbild',
    darkMode: 'Dunkelmodus',
    lightMode: 'Hellmodus',
    notifications: 'Benachrichtigungen',
    privacy: 'Datenschutz',
    help: 'Hilfe',
    about: 'Über',
    logout: 'Abmelden',
    typeMessage: 'Nachricht eingeben...',
    search: 'Suchen',
    newChat: 'Neuer Chat',
    newGroup: 'Neue Gruppe',
    contacts: 'Kontakte',
    online: 'Online',
    offline: 'Offline',
    typing: 'tippt...',
    lastSeen: 'Zuletzt gesehen',
    today: 'Heute',
    yesterday: 'Gestern',
    welcomeBack: 'Willkommen Zurück',
    createAccount: 'Konto Erstellen',
    signIn: 'Anmelden',
    signUp: 'Registrieren',
    continueWithGoogle: 'Mit Google fortfahren',
    continueWithApple: 'Mit Apple fortfahren',
    continueWithFacebook: 'Mit Facebook fortfahren',
    otherSignInOptions: 'Andere Anmeldeoptionen',
    email: 'E-Mail',
    password: 'Passwort',
    username: 'Benutzername',
    displayName: 'Anzeigename',
    forgotPassword: 'Passwort vergessen?',
    dontHaveAccount: 'Kein Konto?',
    alreadyHaveAccount: 'Bereits ein Konto?',
    send: 'Senden',
    cancel: 'Abbrechen',
    save: 'Speichern',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    reply: 'Antworten',
    forward: 'Weiterleiten',
    copy: 'Kopieren',
    aloAssistant: 'ALO Assistent',
    askAlo: 'Frag ALO...',
    listening: 'Hört zu...',
    tapToSpeak: 'Tippen zum Sprechen',
    loading: 'Laden...',
    noMessages: 'Noch keine Nachrichten',
    startConversation: 'Gespräch beginnen',
  },
  it: {
    chats: 'Chat',
    calls: 'Chiamate',
    status: 'Stato',
    channels: 'Canali',
    community: 'Comunità',
    media: 'Media',
    games: 'Giochi',
    ai: 'IA',
    settings: 'Impostazioni',
    general: 'Generale',
    language: 'Lingua',
    selectLanguage: 'Seleziona Lingua',
    appearance: 'Aspetto',
    darkMode: 'Modalità Scura',
    lightMode: 'Modalità Chiara',
    notifications: 'Notifiche',
    privacy: 'Privacy',
    help: 'Aiuto',
    about: 'Info',
    logout: 'Esci',
    typeMessage: 'Scrivi un messaggio...',
    search: 'Cerca',
    newChat: 'Nuova Chat',
    newGroup: 'Nuovo Gruppo',
    contacts: 'Contatti',
    online: 'Online',
    offline: 'Offline',
    typing: 'sta scrivendo...',
    lastSeen: 'Ultimo accesso',
    today: 'Oggi',
    yesterday: 'Ieri',
    welcomeBack: 'Bentornato',
    createAccount: 'Crea Account',
    signIn: 'Accedi',
    signUp: 'Registrati',
    continueWithGoogle: 'Continua con Google',
    continueWithApple: 'Continua con Apple',
    continueWithFacebook: 'Continua con Facebook',
    otherSignInOptions: 'Altre opzioni di accesso',
    email: 'Email',
    password: 'Password',
    username: 'Nome Utente',
    displayName: 'Nome Visualizzato',
    forgotPassword: 'Password dimenticata?',
    dontHaveAccount: 'Non hai un account?',
    alreadyHaveAccount: 'Hai già un account?',
    send: 'Invia',
    cancel: 'Annulla',
    save: 'Salva',
    delete: 'Elimina',
    edit: 'Modifica',
    reply: 'Rispondi',
    forward: 'Inoltra',
    copy: 'Copia',
    aloAssistant: 'Assistente ALO',
    askAlo: 'Chiedi a ALO...',
    listening: 'In ascolto...',
    tapToSpeak: 'Tocca per parlare',
    loading: 'Caricamento...',
    noMessages: 'Nessun messaggio ancora',
    startConversation: 'Inizia una conversazione',
  },
  zh: {
    chats: '聊天',
    calls: '通话',
    status: '状态',
    channels: '频道',
    community: '社区',
    media: '媒体',
    games: '游戏',
    ai: '人工智能',
    settings: '设置',
    general: '通用',
    language: '语言',
    selectLanguage: '选择语言',
    appearance: '外观',
    darkMode: '深色模式',
    lightMode: '浅色模式',
    notifications: '通知',
    privacy: '隐私',
    help: '帮助',
    about: '关于',
    logout: '退出登录',
    typeMessage: '输入消息...',
    search: '搜索',
    newChat: '新聊天',
    newGroup: '新群组',
    contacts: '联系人',
    online: '在线',
    offline: '离线',
    typing: '正在输入...',
    lastSeen: '最后在线',
    today: '今天',
    yesterday: '昨天',
    welcomeBack: '欢迎回来',
    createAccount: '创建账户',
    signIn: '登录',
    signUp: '注册',
    continueWithGoogle: '使用 Google 继续',
    continueWithApple: '使用 Apple 继续',
    continueWithFacebook: '使用 Facebook 继续',
    otherSignInOptions: '其他登录选项',
    email: '邮箱',
    password: '密码',
    username: '用户名',
    displayName: '显示名称',
    forgotPassword: '忘记密码?',
    dontHaveAccount: '没有账户?',
    alreadyHaveAccount: '已有账户?',
    send: '发送',
    cancel: '取消',
    save: '保存',
    delete: '删除',
    edit: '编辑',
    reply: '回复',
    forward: '转发',
    copy: '复制',
    aloAssistant: 'ALO 助手',
    askAlo: '问 ALO...',
    listening: '正在听...',
    tapToSpeak: '点击说话',
    loading: '加载中...',
    noMessages: '还没有消息',
    startConversation: '开始对话',
  },
  ja: {
    chats: 'チャット',
    calls: '通話',
    status: 'ステータス',
    channels: 'チャンネル',
    community: 'コミュニティ',
    media: 'メディア',
    games: 'ゲーム',
    ai: 'AI',
    settings: '設定',
    general: '一般',
    language: '言語',
    selectLanguage: '言語を選択',
    appearance: '外観',
    darkMode: 'ダークモード',
    lightMode: 'ライトモード',
    notifications: '通知',
    privacy: 'プライバシー',
    help: 'ヘルプ',
    about: '概要',
    logout: 'ログアウト',
    typeMessage: 'メッセージを入力...',
    search: '検索',
    newChat: '新しいチャット',
    newGroup: '新しいグループ',
    contacts: '連絡先',
    online: 'オンライン',
    offline: 'オフライン',
    typing: '入力中...',
    lastSeen: '最終オンライン',
    today: '今日',
    yesterday: '昨日',
    welcomeBack: 'おかえりなさい',
    createAccount: 'アカウント作成',
    signIn: 'ログイン',
    signUp: '登録',
    continueWithGoogle: 'Googleで続ける',
    continueWithApple: 'Appleで続ける',
    continueWithFacebook: 'Facebookで続ける',
    otherSignInOptions: '他のログインオプション',
    email: 'メール',
    password: 'パスワード',
    username: 'ユーザー名',
    displayName: '表示名',
    forgotPassword: 'パスワードを忘れた?',
    dontHaveAccount: 'アカウントをお持ちでない?',
    alreadyHaveAccount: 'アカウントをお持ちですか?',
    send: '送信',
    cancel: 'キャンセル',
    save: '保存',
    delete: '削除',
    edit: '編集',
    reply: '返信',
    forward: '転送',
    copy: 'コピー',
    aloAssistant: 'ALOアシスタント',
    askAlo: 'ALOに聞く...',
    listening: '聞いています...',
    tapToSpeak: 'タップして話す',
    loading: '読み込み中...',
    noMessages: 'まだメッセージはありません',
    startConversation: '会話を始める',
  },
  ar: {
    chats: 'المحادثات',
    calls: 'المكالمات',
    status: 'الحالة',
    channels: 'القنوات',
    community: 'المجتمع',
    media: 'الوسائط',
    games: 'الألعاب',
    ai: 'الذكاء الاصطناعي',
    settings: 'الإعدادات',
    general: 'عام',
    language: 'اللغة',
    selectLanguage: 'اختر اللغة',
    appearance: 'المظهر',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    notifications: 'الإشعارات',
    privacy: 'الخصوصية',
    help: 'المساعدة',
    about: 'حول',
    logout: 'تسجيل الخروج',
    typeMessage: 'اكتب رسالة...',
    search: 'بحث',
    newChat: 'محادثة جديدة',
    newGroup: 'مجموعة جديدة',
    contacts: 'جهات الاتصال',
    online: 'متصل',
    offline: 'غير متصل',
    typing: 'يكتب...',
    lastSeen: 'آخر ظهور',
    today: 'اليوم',
    yesterday: 'أمس',
    welcomeBack: 'مرحباً بعودتك',
    createAccount: 'إنشاء حساب',
    signIn: 'تسجيل الدخول',
    signUp: 'التسجيل',
    continueWithGoogle: 'المتابعة مع Google',
    continueWithApple: 'المتابعة مع Apple',
    continueWithFacebook: 'المتابعة مع Facebook',
    otherSignInOptions: 'خيارات تسجيل دخول أخرى',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    username: 'اسم المستخدم',
    displayName: 'اسم العرض',
    forgotPassword: 'نسيت كلمة المرور؟',
    dontHaveAccount: 'ليس لديك حساب؟',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    send: 'إرسال',
    cancel: 'إلغاء',
    save: 'حفظ',
    delete: 'حذف',
    edit: 'تعديل',
    reply: 'رد',
    forward: 'إعادة توجيه',
    copy: 'نسخ',
    aloAssistant: 'مساعد ALO',
    askAlo: 'اسأل ALO...',
    listening: 'جارٍ الاستماع...',
    tapToSpeak: 'انقر للتحدث',
    loading: 'جارٍ التحميل...',
    noMessages: 'لا توجد رسائل بعد',
    startConversation: 'ابدأ محادثة',
  },
  pt: {
    chats: 'Conversas',
    calls: 'Chamadas',
    status: 'Status',
    channels: 'Canais',
    community: 'Comunidade',
    media: 'Mídia',
    games: 'Jogos',
    ai: 'IA',
    settings: 'Configurações',
    general: 'Geral',
    language: 'Idioma',
    selectLanguage: 'Selecionar Idioma',
    appearance: 'Aparência',
    darkMode: 'Modo Escuro',
    lightMode: 'Modo Claro',
    notifications: 'Notificações',
    privacy: 'Privacidade',
    help: 'Ajuda',
    about: 'Sobre',
    logout: 'Sair',
    typeMessage: 'Digite uma mensagem...',
    search: 'Pesquisar',
    newChat: 'Nova Conversa',
    newGroup: 'Novo Grupo',
    contacts: 'Contatos',
    online: 'Online',
    offline: 'Offline',
    typing: 'digitando...',
    lastSeen: 'Visto por último',
    today: 'Hoje',
    yesterday: 'Ontem',
    welcomeBack: 'Bem-vindo de Volta',
    createAccount: 'Criar Conta',
    signIn: 'Entrar',
    signUp: 'Cadastrar',
    continueWithGoogle: 'Continuar com Google',
    continueWithApple: 'Continuar com Apple',
    continueWithFacebook: 'Continuar com Facebook',
    otherSignInOptions: 'Outras opções de login',
    email: 'E-mail',
    password: 'Senha',
    username: 'Nome de usuário',
    displayName: 'Nome de exibição',
    forgotPassword: 'Esqueceu a senha?',
    dontHaveAccount: 'Não tem uma conta?',
    alreadyHaveAccount: 'Já tem uma conta?',
    send: 'Enviar',
    cancel: 'Cancelar',
    save: 'Salvar',
    delete: 'Excluir',
    edit: 'Editar',
    reply: 'Responder',
    forward: 'Encaminhar',
    copy: 'Copiar',
    aloAssistant: 'Assistente ALO',
    askAlo: 'Pergunte ao ALO...',
    listening: 'Ouvindo...',
    tapToSpeak: 'Toque para falar',
    loading: 'Carregando...',
    noMessages: 'Sem mensagens ainda',
    startConversation: 'Iniciar conversa',
  },
  ru: {
    chats: 'Чаты',
    calls: 'Звонки',
    status: 'Статус',
    channels: 'Каналы',
    community: 'Сообщество',
    media: 'Медиа',
    games: 'Игры',
    ai: 'ИИ',
    settings: 'Настройки',
    general: 'Общие',
    language: 'Язык',
    selectLanguage: 'Выбрать язык',
    appearance: 'Оформление',
    darkMode: 'Тёмный режим',
    lightMode: 'Светлый режим',
    notifications: 'Уведомления',
    privacy: 'Конфиденциальность',
    help: 'Помощь',
    about: 'О программе',
    logout: 'Выйти',
    typeMessage: 'Введите сообщение...',
    search: 'Поиск',
    newChat: 'Новый чат',
    newGroup: 'Новая группа',
    contacts: 'Контакты',
    online: 'В сети',
    offline: 'Не в сети',
    typing: 'печатает...',
    lastSeen: 'Был(а)',
    today: 'Сегодня',
    yesterday: 'Вчера',
    welcomeBack: 'С возвращением',
    createAccount: 'Создать аккаунт',
    signIn: 'Войти',
    signUp: 'Регистрация',
    continueWithGoogle: 'Продолжить с Google',
    continueWithApple: 'Продолжить с Apple',
    continueWithFacebook: 'Продолжить с Facebook',
    otherSignInOptions: 'Другие способы входа',
    email: 'Эл. почта',
    password: 'Пароль',
    username: 'Имя пользователя',
    displayName: 'Отображаемое имя',
    forgotPassword: 'Забыли пароль?',
    dontHaveAccount: 'Нет аккаунта?',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    send: 'Отправить',
    cancel: 'Отмена',
    save: 'Сохранить',
    delete: 'Удалить',
    edit: 'Редактировать',
    reply: 'Ответить',
    forward: 'Переслать',
    copy: 'Копировать',
    aloAssistant: 'Ассистент ALO',
    askAlo: 'Спросите ALO...',
    listening: 'Слушаю...',
    tapToSpeak: 'Нажмите, чтобы говорить',
    loading: 'Загрузка...',
    noMessages: 'Сообщений пока нет',
    startConversation: 'Начать разговор',
  },
  ko: {
    chats: '채팅',
    calls: '통화',
    status: '상태',
    channels: '채널',
    community: '커뮤니티',
    media: '미디어',
    games: '게임',
    ai: 'AI',
    settings: '설정',
    general: '일반',
    language: '언어',
    selectLanguage: '언어 선택',
    appearance: '외관',
    darkMode: '다크 모드',
    lightMode: '라이트 모드',
    notifications: '알림',
    privacy: '개인정보',
    help: '도움말',
    about: '정보',
    logout: '로그아웃',
    typeMessage: '메시지 입력...',
    search: '검색',
    newChat: '새 채팅',
    newGroup: '새 그룹',
    contacts: '연락처',
    online: '온라인',
    offline: '오프라인',
    typing: '입력 중...',
    lastSeen: '마지막 접속',
    today: '오늘',
    yesterday: '어제',
    welcomeBack: '다시 오신 것을 환영합니다',
    createAccount: '계정 만들기',
    signIn: '로그인',
    signUp: '가입',
    continueWithGoogle: 'Google로 계속',
    continueWithApple: 'Apple로 계속',
    continueWithFacebook: 'Facebook으로 계속',
    otherSignInOptions: '다른 로그인 옵션',
    email: '이메일',
    password: '비밀번호',
    username: '사용자 이름',
    displayName: '표시 이름',
    forgotPassword: '비밀번호를 잊으셨나요?',
    dontHaveAccount: '계정이 없으신가요?',
    alreadyHaveAccount: '이미 계정이 있으신가요?',
    send: '보내기',
    cancel: '취소',
    save: '저장',
    delete: '삭제',
    edit: '수정',
    reply: '답장',
    forward: '전달',
    copy: '복사',
    aloAssistant: 'ALO 어시스턴트',
    askAlo: 'ALO에게 물어보세요...',
    listening: '듣는 중...',
    tapToSpeak: '탭하여 말하기',
    loading: '로딩 중...',
    noMessages: '아직 메시지가 없습니다',
    startConversation: '대화 시작',
  },
  hi: {
    chats: 'चैट',
    calls: 'कॉल',
    status: 'स्थिति',
    channels: 'चैनल',
    community: 'समुदाय',
    media: 'मीडिया',
    games: 'गेम्स',
    ai: 'AI',
    settings: 'सेटिंग्स',
    general: 'सामान्य',
    language: 'भाषा',
    selectLanguage: 'भाषा चुनें',
    appearance: 'दिखावट',
    darkMode: 'डार्क मोड',
    lightMode: 'लाइट मोड',
    notifications: 'सूचनाएं',
    privacy: 'गोपनीयता',
    help: 'मदद',
    about: 'के बारे में',
    logout: 'लॉग आउट',
    typeMessage: 'संदेश लिखें...',
    search: 'खोजें',
    newChat: 'नई चैट',
    newGroup: 'नया ग्रुप',
    contacts: 'संपर्क',
    online: 'ऑनलाइन',
    offline: 'ऑफ़लाइन',
    typing: 'टाइप कर रहा है...',
    lastSeen: 'अंतिम बार देखा',
    today: 'आज',
    yesterday: 'कल',
    welcomeBack: 'वापसी पर स्वागत है',
    createAccount: 'खाता बनाएं',
    signIn: 'साइन इन करें',
    signUp: 'साइन अप करें',
    continueWithGoogle: 'Google से जारी रखें',
    continueWithApple: 'Apple से जारी रखें',
    continueWithFacebook: 'Facebook से जारी रखें',
    otherSignInOptions: 'अन्य साइन इन विकल्प',
    email: 'ईमेल',
    password: 'पासवर्ड',
    username: 'उपयोगकर्ता नाम',
    displayName: 'प्रदर्शन नाम',
    forgotPassword: 'पासवर्ड भूल गए?',
    dontHaveAccount: 'खाता नहीं है?',
    alreadyHaveAccount: 'पहले से खाता है?',
    send: 'भेजें',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    reply: 'जवाब दें',
    forward: 'आगे भेजें',
    copy: 'कॉपी करें',
    aloAssistant: 'ALO सहायक',
    askAlo: 'ALO से पूछें...',
    listening: 'सुन रहा है...',
    tapToSpeak: 'बोलने के लिए टैप करें',
    loading: 'लोड हो रहा है...',
    noMessages: 'अभी तक कोई संदेश नहीं',
    startConversation: 'बातचीत शुरू करें',
  },
};

// Create the context
const LanguageContext = createContext();

// Provider component
export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    // Get saved language from localStorage - ONLY use saved preference
    const saved = localStorage.getItem('appLanguage');
    if (saved && LANGUAGES[saved]) return saved;
    
    // Default to Italian for FaceConnect Desktop
    return 'it';
  });

  useEffect(() => {
    localStorage.setItem('appLanguage', language);
    // Set document direction for RTL languages
    document.documentElement.dir = ['ar', 'he', 'fa', 'ur'].includes(language) ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  // Listen for language changes from Electron menu
  useEffect(() => {
    if (window.electronAPI?.onLanguageChange) {
      window.electronAPI.onLanguageChange((langCode) => {
        if (LANGUAGES[langCode]) {
          setLanguage(langCode);
          console.log(`Language changed from Electron menu: ${langCode}`);
        }
      });
    }
    
    // Cleanup
    return () => {
      if (window.electronAPI?.removeUpdateListeners) {
        // This also removes language listeners
      }
    };
  }, []);

  // Translation function
  const t = (key) => {
    // Get translation for current language, fallback to English
    const langTranslations = translations[language] || translations.en;
    return langTranslations[key] || translations.en[key] || key;
  };

  const value = {
    language,
    setLanguage,
    t,
    languages: LANGUAGES,
    isRTL: ['ar', 'he', 'fa', 'ur'].includes(language),
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

// Hook to use language context
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;
